import { useState, useEffect, useRef } from "react";

const C = {
  ocean:"#42708C", sky:"#7EADBF", earth:"#8C6746", coral:"#F25A38",
  fog:"#F2F2F2", white:"#FFFFFF", dark:"#2C2C2A", mid:"#5F5E5A", light:"#B4B2A9",
};

const FAMILY_COLOR = {
  "Romance":"#F25A38","Germanic":"#7EADBF","Slavic":"#42708C","Semitic":"#8C6746",
  "Sino-Tibetan":"#C0796A","Japonic":"#D4906A","Koreanic":"#5A9BAD","Austroasiatic":"#6B9E8C",
  "Kra-Dai":"#9BBFCE","Indo-Iranian":"#B8875A","Turkic":"#A07850","Niger-Congo (Bantu)":"#7DA870",
  "Niger-Congo":"#7DA870","Austronesian":"#6EAAB5","Hellenic":"#7B8CC2","Uralic":"#8FAABC",
  "Kartvelian":"#C08090","Mongolic":"#9E8870","Hmong-Mien":"#B07AB0","Quechuan":"#C09A40",
  "Mayan":"#70A890","Na-Dené":"#A08060","Dravidian":"#C07860","Uto-Aztecan":"#B09060",
  "Tupian":"#80A870","Afro-Asiatic":"#B89060","Tibeto-Burman":"#9080C0",
  "Indo-European (isolate)":"#A090C0","Celtic":"#6080A0","Baltic":"#80A0C0",
  "Language isolate":"#A0A080",
};

const LANG_FLAGS = {
  "French":"🇫🇷","Spanish":"🇪🇸","Portuguese":"🇧🇷","Italian":"🇮🇹","Romanian":"🇷🇴",
  "German":"🇩🇪","Dutch":"🇳🇱","Swedish":"🇸🇪","Norwegian":"🇳🇴","Russian":"🇷🇺",
  "Ukrainian":"🇺🇦","Bulgarian":"🇧🇬","Serbian":"🇷🇸","Mongolian":"🇲🇳","Arabic":"🇸🇦",
  "Persian (Farsi)":"🇮🇷","Urdu":"🇵🇰","Hebrew":"🇮🇱","Amharic":"🇪🇹","Mandarin Chinese":"🇨🇳",
  "Cantonese":"🇭🇰","Japanese":"🇯🇵","Korean":"🇰🇷","Vietnamese":"🇻🇳","Thai":"🇹🇭",
  "Khmer":"🇰🇭","Myanmar (Burmese)":"🇲🇲","Hindi":"🇮🇳","Nepali":"🇳🇵","Bengali":"🇧🇩",
  "Tamil":"🇱🇰","Kannada":"🇮🇳","Telugu":"🇮🇳","Turkish":"🇹🇷","Swahili":"🇰🇪",
  "Yoruba":"🇳🇬","Zulu":"🇿🇦","Greek":"🇬🇷","Georgian":"🇬🇪","Armenian":"🇦🇲",
  "Finnish":"🇫🇮","Hungarian":"🇭🇺","Hmong":"🌏","Quechua":"🇵🇪","Nahuatl":"🇲🇽",
  "Guaraní":"🇵🇾","Maya (Yucatec)":"🇲🇽","Navajo":"🇺🇸","Hawaiian":"🇺🇸","Māori":"🇳🇿",
  "Tibetan":"🏔️","Wolof":"🇸🇳","Tigrinya":"🇪🇷","Tetum":"🇹🇱",
  "Catalan":"🏳️","Galician":"🏴","Basque":"🏴","Welsh":"🏴󠁧󠁢󠁷󠁬󠁳󠁿",
  "Irish":"🇮🇪","Scottish Gaelic":"🏴󠁧󠁢󠁳󠁣󠁴󠁿","Breton":"🏳️","Maltese":"🇲🇹",
  "Albanian":"🇦🇱","Macedonian":"🇲🇰","Slovenian":"🇸🇮","Croatian":"🇭🇷",
  "Slovak":"🇸🇰","Lithuanian":"🇱🇹","Latvian":"🇱🇻","Estonian":"🇪🇪",
  "Belarusian":"🇧🇾","Luxembourgish":"🇱🇺","Faroese":"🇫🇴","Icelandic":"🇮🇸",
  "Afrikaans":"🇿🇦","Occitan":"🏳️","Azerbaijani":"🇦🇿","Uzbek":"🇺🇿",
  "Kazakh":"🇰🇿","Kyrgyz":"🇰🇬","Tajik":"🇹🇯","Pashto":"🇦🇫","Sinhala":"🇱🇰",
  "Lao":"🇱🇦","Tagalog":"🇵🇭","Malay":"🇲🇾","Javanese":"🇮🇩","Uyghur":"🌏",
  "Marathi":"🇮🇳","Gujarati":"🇮🇳","Punjabi":"🇮🇳","Odia":"🇮🇳","Dzongkha":"🇧🇹",
};

const CONGRATS = [
  "Nailed it! 🎯","You legend! 🌟","Spot on! ✨","Impressive! 🔥","Brilliant! 💡",
  "Outstanding! 🏆","Sharp eye! 👁️","Polyglot vibes! 🌍","That's the one! 💪","Unstoppable! 🚀",
];

const LANGUAGES = [
  // ── ROMANCE ──
  { name:"French", family:"Romance", region:"Europe", script:"Latin", speakers:"~310M",
    tip:"Look for accented vowels like é, è, ê, and the cedilla ç. The combination 'eau' and frequent apostrophes are very French.",
    confusables:["Italian","Spanish","Portuguese","Romanian","Catalan"],
    quotes:[{s:"La seule façon de faire du bon travail est d'aimer ce que vous faites.",t:"The only way to do great work is to love what you do."},{s:"La vie est ce qui se passe pendant qu'on fait d'autres projets.",t:"Life is what happens while you're busy making other plans."},{s:"Soyez le changement que vous voulez voir dans le monde.",t:"Be the change you wish to see in the world."}]},
  { name:"Spanish", family:"Romance", region:"Europe / Americas", script:"Latin", speakers:"~500M",
    tip:"Spot the inverted ¿ and ¡ at sentence starts. The letter ñ and ll/rr combinations are distinctively Spanish.",
    confusables:["Portuguese","Italian","French","Romanian","Catalan"],
    quotes:[{s:"No importa cuán lento vayas, siempre y cuando no te detengas.",t:"It doesn't matter how slowly you go, as long as you don't stop."},{s:"La vida es sueño, y los sueños, sueños son.",t:"Life is a dream, and dreams are just dreams."},{s:"Dime con quién andas y te diré quién eres.",t:"Tell me who you walk with and I'll tell you who you are."}]},
  { name:"Portuguese", family:"Romance", region:"Europe / Americas", script:"Latin", speakers:"~260M",
    tip:"Look for unique ã and õ nasal vowels with tilde, and words ending in -ão, -ção.",
    confusables:["Spanish","Italian","French","Romanian","Galician"],
    quotes:[{s:"A vida é o que acontece enquanto estamos ocupados fazendo outros planos.",t:"Life is what happens while we are busy making other plans."},{s:"Quem não arrisca não petisca.",t:"Nothing ventured, nothing gained."},{s:"A sabedoria começa com o silêncio.",t:"Wisdom begins with silence."}]},
  { name:"Italian", family:"Romance", region:"Europe", script:"Latin", speakers:"~67M",
    tip:"Italian loves double consonants (ll, tt, cc) and words ending in vowels. Look for -zione, -mente endings.",
    confusables:["Spanish","Portuguese","French","Romanian","Catalan"],
    quotes:[{s:"La vita è bella quando hai qualcuno con cui condividerla.",t:"Life is beautiful when you have someone to share it with."},{s:"Chi dorme non piglia pesci.",t:"He who sleeps doesn't catch fish."},{s:"Tutto è bene quel che finisce bene.",t:"All's well that ends well."}]},
  { name:"Romanian", family:"Romance", region:"Europe", script:"Latin", speakers:"~24M",
    tip:"Romanian is unique among Romance languages for letters ă, â, î, ș, ț. It looks vaguely Italian but has Slavic-influenced spellings.",
    confusables:["Italian","Spanish","Portuguese","French","Catalan"],
    quotes:[{s:"Omul sfințește locul, nu locul pe om.",t:"The person sanctifies the place, not the place the person."},{s:"Graba strică treaba.",t:"Haste makes waste."},{s:"Vorba dulce mult aduce.",t:"Sweet words bring much."}]},
  { name:"Catalan", family:"Romance", region:"Europe", script:"Latin", speakers:"~10M",
    tip:"Catalan looks like a blend of Spanish and French. Key giveaways: the midpoint dot (·) in words like col·legi, the letters l·l, and endings like -ció, -ment. No ñ unlike Spanish.",
    confusables:["Spanish","Portuguese","French","Italian","Occitan"],
    quotes:[{s:"Qui no s'arrisca, no pisca.",t:"Nothing ventured, nothing gained."},{s:"Val més tard que mai.",t:"Better late than never."},{s:"L'home proposa i Déu disposa.",t:"Man proposes and God disposes."}]},
  { name:"Galician", family:"Romance", region:"Europe", script:"Latin", speakers:"~2.4M",
    tip:"Galician looks very close to Portuguese — the nh and lh digraphs appear, as does ó and á. Unlike Spanish, no ñ. Very similar to old Portuguese.",
    confusables:["Portuguese","Spanish","Catalan","Italian","Occitan"],
    quotes:[{s:"Quen non arrisca, non gaña.",t:"He who doesn't risk, doesn't gain."},{s:"A lingua é a alma do pobo.",t:"Language is the soul of the people."},{s:"Máis vale tarde que nunca.",t:"Better late than never."}]},
  { name:"Occitan", family:"Romance", region:"Europe", script:"Latin", speakers:"~200K",
    tip:"Occitan looks like a blend of French, Spanish, and Catalan. Look for words ending in -oc, -al, -an and the letters ç, à, è. Often confused with Catalan.",
    confusables:["Catalan","French","Spanish","Italian","Breton"],
    quotes:[{s:"La lenga es l'ama del pòble.",t:"Language is the soul of the people."},{s:"Qui cerca, trapa.",t:"He who seeks, finds."}]},
  { name:"Maltese", family:"Semitic", region:"Europe", script:"Latin", speakers:"~520K",
    tip:"Maltese is the only Semitic language written in Latin script. It has Arabic roots but heavy Italian/English influence. Look for the unique letters għ, ħ, and ċ.",
    confusables:["Arabic","Italian","Hebrew","Catalan","Sicilian"],
    quotes:[{s:"Min jitħabat, jirbaħ.",t:"He who strives, wins."},{s:"Il-kelma tajba tiftaħ il-bibien kollha.",t:"A good word opens all doors."},{s:"L-għaqal fl-għajnejn u l-imħabba fil-qalb.",t:"Wisdom is in the eyes, love is in the heart."}]},

  // ── GERMANIC ──
  { name:"German", family:"Germanic", region:"Europe", script:"Latin", speakers:"~135M",
    tip:"German capitalizes ALL nouns. Look for long compound words, umlauts (ä, ö, ü), and the sharp ß.",
    confusables:["Dutch","Swedish","Norwegian","Luxembourgish","Afrikaans"],
    quotes:[{s:"Der Mensch wächst mit seinen Aufgaben.",t:"A person grows with their tasks."},{s:"Übung macht den Meister.",t:"Practice makes perfect."},{s:"Was dich nicht umbringt, macht dich stärker.",t:"What doesn't kill you makes you stronger."}]},
  { name:"Dutch", family:"Germanic", region:"Europe", script:"Latin", speakers:"~25M",
    tip:"Dutch has distinctive double vowels (aa, ee, oo) and the unique ij digraph. Look for 'de', 'het', 'een' and 'sch'.",
    confusables:["German","Afrikaans","Swedish","Norwegian","Luxembourgish"],
    quotes:[{s:"Wie niet waagt, die niet wint.",t:"Who dares not, wins not."},{s:"Oost west, thuis best.",t:"East or west, home is best."},{s:"Goed voorbeeld doet goed volgen.",t:"Good example leads to good following."}]},
  { name:"Swedish", family:"Germanic", region:"Europe", script:"Latin", speakers:"~13M",
    tip:"Swedish has three extra letters: å, ä, ö. Distinctive words include 'och' (and) and 'att' (to). Cleaner-looking than German.",
    confusables:["Norwegian","Danish","Dutch","German","Finnish"],
    quotes:[{s:"Det är inte hur långt du faller, utan hur högt du studsar.",t:"It is not how far you fall, but how high you bounce."},{s:"Lär av gårdagen, lev för idag, hoppas på morgondagen.",t:"Learn from yesterday, live for today, hope for tomorrow."},{s:"Den som gapar efter mycket mister ofta hela stycket.",t:"He who grabs for too much often loses it all."}]},
  { name:"Norwegian", family:"Germanic", region:"Europe", script:"Latin", speakers:"~5M",
    tip:"Norwegian shares å, æ, ø with Danish. Very similar to Swedish but uses 'ikke' differently. Look for words ending in -ig, -lig.",
    confusables:["Swedish","Danish","Dutch","German","Faroese"],
    quotes:[{s:"Det er ikke fjellene foran deg som sliter deg ut, men steinen i skoen din.",t:"It is not the mountains ahead that wear you out, but the pebble in your shoe."},{s:"Den som ler sist, ler best.",t:"He who laughs last, laughs best."},{s:"Veien blir til mens du går.",t:"The road is made by walking."}]},
  { name:"Luxembourgish", family:"Germanic", region:"Europe", script:"Latin", speakers:"~390K",
    tip:"Luxembourgish looks like German but with French loanwords and unique spellings. The letter combination 'äi' and 'éi' are distinctive. Words like 'Ech' (I) and 'ass' (is) are giveaways.",
    confusables:["German","Dutch","Afrikaans","French","Alsatian"],
    quotes:[{s:"Wann een net probéiert, kann een net gewannen.",t:"If one doesn't try, one cannot win."},{s:"D'Sprooch ass d'Séil vum Vollek.",t:"Language is the soul of the people."}]},
  { name:"Faroese", family:"Germanic", region:"Europe", script:"Latin", speakers:"~72K",
    tip:"Faroese looks like Icelandic with some Norwegian influence. Uses eth (ð) and the letters á, í, ó, ú, ý, æ. The combination 'hv' (pronounced kv) and 'gj' are distinctive.",
    confusables:["Icelandic","Norwegian","Danish","Swedish","Breton"],
    quotes:[{s:"Tað sum ikki drepur, harðnar.",t:"What doesn't kill you makes you stronger."},{s:"Tíðin fer, men minningar liva.",t:"Time passes, but memories live on."}]},
  { name:"Icelandic", family:"Germanic", region:"Europe", script:"Latin", speakers:"~370K",
    tip:"Icelandic uniquely preserves eth (ð) and thorn (þ) from Old Norse. Look for þ at word starts (pronounced 'th') and ð in the middle of words. Also uses á, é, í, ó, ú, ý, ö, æ.",
    confusables:["Faroese","Norwegian","Danish","Swedish","Breton"],
    quotes:[{s:"Þolinmæði er móðir allra dyggða.",t:"Patience is the mother of all virtues."},{s:"Sá er vitr, er þegir.",t:"He is wise who stays silent."},{s:"Lífið er stutt, nýttu það vel.",t:"Life is short, use it well."}]},
  { name:"Afrikaans", family:"Germanic", region:"Africa", script:"Latin", speakers:"~7M",
    tip:"Afrikaans looks like simplified Dutch — no grammatical gender, no verb conjugation for person. Words like 'die' (the), 'is', 'nie' (not) appear very frequently. The double negative 'nie...nie' is a unique giveaway.",
    confusables:["Dutch","German","Flemish","Low German","Frisian"],
    quotes:[{s:"'n Boer maak 'n plan.",t:"A farmer makes a plan — meaning resourcefulness."},{s:"Sonder taal, sonder siel.",t:"Without language, without soul."},{s:"Geduld is 'n deug.",t:"Patience is a virtue."}]},

  // ── CELTIC ──
  { name:"Welsh", family:"Celtic", region:"Europe", script:"Latin", speakers:"~880K",
    tip:"Welsh uses striking consonant clusters: 'dd' (like 'th'), 'll' (a voiceless lateral), 'rh', 'ch', 'ng'. Words like 'dw i'n' and 'mae' are distinctively Welsh.",
    confusables:["Breton","Irish","Scottish Gaelic","Cornish","Icelandic"],
    quotes:[{s:"Nid aur yw popeth melyn.",t:"All that glitters is not gold."},{s:"Heb iaith, heb galon.",t:"Without language, without heart."},{s:"Dyfal donc a dyr y garreg.",t:"Persistent tapping breaks the stone."}]},
  { name:"Irish", family:"Celtic", region:"Europe", script:"Latin", speakers:"~1.8M",
    tip:"Irish (Gaeilge) has radical initial mutations — words change their first letter. The combination 'mh' and 'bh' are pronounced 'v'. Very unusual spelling-to-sound relationship.",
    confusables:["Welsh","Scottish Gaelic","Breton","Cornish","Faroese"],
    quotes:[{s:"Is fearr Gaeilge bhriste ná Béarla cliste.",t:"Broken Irish is better than clever English."},{s:"Ní neart go cur le chéile.",t:"There is no strength without unity."},{s:"Maireann croí éadrom i bhfad.",t:"A light heart lives longest."}]},
  { name:"Scottish Gaelic", family:"Celtic", region:"Europe", script:"Latin", speakers:"~57K",
    tip:"Scottish Gaelic looks like Irish but uses grave accents only (à, è, ì, ò, ù) while Irish uses acute. Look for 'tha' (is) very frequently and apostrophes for contractions.",
    confusables:["Irish","Welsh","Breton","Faroese","Icelandic"],
    quotes:[{s:"Is treasa tuath ná tighearna.",t:"The people are stronger than a lord."},{s:"Buannaichidh foighidinn.",t:"Patience will prevail."}]},
  { name:"Breton", family:"Celtic", region:"Europe", script:"Latin", speakers:"~210K",
    tip:"Breton is a Celtic language of northwest France. Look for 'c'h' (a guttural sound), 'ch', and frequent 'z' and 'v'. Words often end in consonants unlike French. Resembles Welsh more than French.",
    confusables:["Welsh","Irish","French","Scottish Gaelic","Occitan"],
    quotes:[{s:"Ar pezh a vez kavet en douar a vez kavet er galon.",t:"What is found in the earth is found in the heart."}]},

  // ── SLAVIC ──
  { name:"Russian", family:"Slavic", region:"Europe / Asia", script:"Cyrillic", speakers:"~258M",
    tip:"Russian Cyrillic has Ж, Щ, Ъ, Ы, Э. Look for the hard sign ъ and the letter ы — unique to Russian.",
    confusables:["Ukrainian","Bulgarian","Serbian","Macedonian","Mongolian"],
    quotes:[{s:"Не тот велик, кто никогда не падал, а тот велик, кто падал и вставал.",t:"Not the one who never fell is great, but the one who fell and rose again."},{s:"Терпение и труд всё перетрут.",t:"Patience and hard work will overcome everything."},{s:"Без труда не выловишь и рыбку из пруда.",t:"Without effort, you can't even pull a fish from a pond."}]},
  { name:"Ukrainian", family:"Slavic", region:"Europe", script:"Cyrillic", speakers:"~40M",
    tip:"Ukrainian has unique letters І, Ї, Є, and Ґ not found in Russian. It also lacks the Russian Ъ and Ы.",
    confusables:["Russian","Bulgarian","Serbian","Macedonian","Belarusian"],
    quotes:[{s:"Де є воля, там є і шлях.",t:"Where there is a will, there is a way."},{s:"Не май сто рублів, а май сто друзів.",t:"Don't have a hundred rubles, have a hundred friends."},{s:"Хто рано встає, тому Бог дає.",t:"God gives to those who rise early."}]},
  { name:"Bulgarian", family:"Slavic", region:"Europe", script:"Cyrillic", speakers:"~8M",
    tip:"Bulgarian Cyrillic looks similar to Russian but uses Ъ frequently as a vowel. It has no ы, ё, or э like Russian.",
    confusables:["Russian","Ukrainian","Macedonian","Serbian","Mongolian"],
    quotes:[{s:"Търпението е горчиво, но плодовете му са сладки.",t:"Patience is bitter, but its fruits are sweet."},{s:"Каквото посееш, това ще пожънеш.",t:"You reap what you sow."},{s:"Без мъка няма наука.",t:"No pain, no gain."}]},
  { name:"Serbian", family:"Slavic", region:"Europe", script:"Cyrillic", speakers:"~12M",
    tip:"Serbian Cyrillic includes Љ, Њ, Џ — not in Russian or Ukrainian. These represent lj, nj, dz sounds unique to South Slavic.",
    confusables:["Russian","Bulgarian","Ukrainian","Macedonian","Mongolian"],
    quotes:[{s:"Дунав пролази кроз многе земље Европе и носи са собом историју векова.",t:"The Danube flows through many lands, carrying the history of centuries."},{s:"Ко рано рани, две среће граби.",t:"He who rises early catches two fortunes."}]},
  { name:"Macedonian", family:"Slavic", region:"Europe", script:"Cyrillic", speakers:"~2M",
    tip:"Macedonian Cyrillic is close to Bulgarian and Serbian. Unique letters include Ѓ and Ќ (soft g and k sounds) not found in Russian or Ukrainian.",
    confusables:["Bulgarian","Serbian","Russian","Ukrainian","Mongolian"],
    quotes:[{s:"Трпение носи среќа.",t:"Patience brings happiness."},{s:"Знаењето е моќ.",t:"Knowledge is power."}]},
  { name:"Slovenian", family:"Slavic", region:"Europe", script:"Latin", speakers:"~2.5M",
    tip:"Slovenian uses Latin with three extra letters: č, š, ž. It has a unique dual grammatical number. Look for the word 'je' (is) and frequent -ski, -ška endings.",
    confusables:["Croatian","Serbian","Czech","Slovak","Polish"],
    quotes:[{s:"Kdor išče, ta najde.",t:"He who seeks, finds."},{s:"Bolje vrabec v roki kot golob na strehi.",t:"Better a sparrow in the hand than a pigeon on the roof."},{s:"Jezik je most med ljudmi.",t:"Language is a bridge between people."}]},
  { name:"Croatian", family:"Slavic", region:"Europe", script:"Latin", speakers:"~5.5M",
    tip:"Croatian uses Latin with č, ć, š, ž, đ. The letters ć and đ distinguish it from Serbian. Look for consonant clusters like 'sv', 'str', 'kr'.",
    confusables:["Slovenian","Serbian","Slovak","Czech","Polish"],
    quotes:[{s:"Bolje spriječiti nego liječiti.",t:"Better to prevent than to cure."},{s:"Tko traži, taj i nalazi.",t:"He who seeks, finds."},{s:"Riječ je srebro, šutnja je zlato.",t:"Speech is silver, silence is gold."}]},
  { name:"Polish", family:"Slavic", region:"Europe", script:"Latin", speakers:"~45M",
    tip:"Polish uses Latin with ą, ę, ó, ś, ź, ż, ć, ń, ł. The crossed ł (pronounced 'w') and the nasal ą, ę are unique giveaways. Many consonant clusters like 'szcz'.",
    confusables:["Czech","Slovak","Slovenian","Croatian","Lithuanian"],
    quotes:[{s:"Polska kuchnia jest bogata w smaki i tradycje.",t:"Polish cuisine is rich in flavors and traditions."},{s:"Nie ma tego złego, co by na dobre nie wyszło.",t:"There is no evil that doesn't turn into something good."}]},
  { name:"Slovak", family:"Slavic", region:"Europe", script:"Latin", speakers:"~5M",
    tip:"Slovak uses Latin with č, š, ž and uniquely the letters ľ (soft l) and ĺ, ŕ (syllabic consonants). The diacritic ˇ (háček) and ´ (dĺžeň) appear frequently.",
    confusables:["Czech","Slovenian","Polish","Croatian","Ukrainian"],
    quotes:[{s:"Kde je vôľa, tam je aj cesta.",t:"Where there is a will, there is a way."},{s:"Trpezlivosť ruže prináša.",t:"Patience brings roses."}]},
  { name:"Czech", family:"Slavic", region:"Europe", script:"Latin", speakers:"~10M",
    tip:"Czech uses Latin with č, š, ž, ř (a unique trilled fricative), and long vowels á, é, í, ó, ú, ů. The letter ř is found in no other language.",
    confusables:["Slovak","Slovenian","Polish","Croatian","Lithuanian"],
    quotes:[{s:"Praha je jedno z nejkrásnějších měst v Evropě.",t:"Prague is one of the most beautiful cities in Europe."},{s:"Bez práce nejsou koláče.",t:"Without work there are no cakes — no pain, no gain."}]},
  { name:"Belarusian", family:"Slavic", region:"Europe", script:"Cyrillic", speakers:"~5M",
    tip:"Belarusian Cyrillic has the unique letter Ў (short u) — a semi-vowel with a breve above it. This letter appears in no other Cyrillic alphabet.",
    confusables:["Russian","Ukrainian","Bulgarian","Polish","Macedonian"],
    quotes:[{s:"Хто шукае, той знаходзіць.",t:"He who seeks, finds."},{s:"Мова — душа народа.",t:"Language is the soul of the people."}]},

  // ── BALTIC ──
  { name:"Lithuanian", family:"Baltic", region:"Europe", script:"Latin", speakers:"~3M",
    tip:"Lithuanian is one of the oldest Indo-European languages. Look for the letters ą, č, ę, ė, į, š, ų, ū, ž. Words tend to be long with many noun case endings. The double vowels ė and ū are distinctive.",
    confusables:["Latvian","Estonian","Polish","Finnish","Czech"],
    quotes:[{s:"Kas ieško, tas randa.",t:"He who seeks, finds."},{s:"Geriau vėliau negu niekada.",t:"Better late than never."},{s:"Draugystė – didžiausia vertybė.",t:"Friendship is the greatest value."}]},
  { name:"Latvian", family:"Baltic", region:"Europe", script:"Latin", speakers:"~1.5M",
    tip:"Latvian uses macrons (ā, ē, ī, ū) for long vowels and has č, ģ, ķ, ļ, ņ, š, ž. Look for words ending in -s (masculine) and -a (feminine) on almost all nouns.",
    confusables:["Lithuanian","Estonian","Finnish","Slovenian","Czech"],
    quotes:[{s:"Kas meklē, tas atrod.",t:"He who seeks, finds."},{s:"Labāk vēlu, nekā nekad.",t:"Better late than never."},{s:"Valoda ir tautas dvēsele.",t:"Language is the soul of the nation."}]},

  // ── URALIC ──
  { name:"Finnish", family:"Uralic", region:"Europe", script:"Latin", speakers:"~5M",
    tip:"Finnish has no articles, double vowels and consonants everywhere (aa, ee, ll, kk), very long words, and common letters ä and ö.",
    confusables:["Estonian","Hungarian","Turkish","Swedish","Lithuanian"],
    quotes:[{s:"Ei se ole viisas, joka viisaasti ei puhu.",t:"It is not wise who does not speak wisely."},{s:"Työ tekijäänsä kiittää.",t:"Work praises its maker."},{s:"Parempi myöhään kuin ei milloinkaan.",t:"Better late than never."}]},
  { name:"Hungarian", family:"Uralic", region:"Europe", script:"Latin", speakers:"~13M",
    tip:"Hungarian uses long vowels with double accents: á, é, í, ó, ő, ú, ű. The double-acute ő and ű are unique to Hungarian.",
    confusables:["Finnish","Estonian","Turkish","Romanian","Czech"],
    quotes:[{s:"Aki mer, az nyer.",t:"He who dares, wins."},{s:"Lassan járj, tovább érsz.",t:"Go slowly, you'll get further."},{s:"Több szem többet lát.",t:"More eyes see more."}]},
  { name:"Estonian", family:"Uralic", region:"Europe", script:"Latin", speakers:"~1.1M",
    tip:"Estonian is related to Finnish, not to Latvian or Lithuanian. Look for the three vowel lengths and the unique letters õ, ä, ö, ü. Very long compound words and no grammatical gender.",
    confusables:["Finnish","Latvian","Lithuanian","Hungarian","Swedish"],
    quotes:[{s:"Kus viga näed laita, seal täida ise.",t:"Where you see a fault, fix it yourself."},{s:"Töö kiidab tegijat.",t:"Work praises its maker."},{s:"Parem hilja kui mitte kunagi.",t:"Better late than never."}]},

  // ── OTHER EUROPEAN ──
  { name:"Greek", family:"Hellenic", region:"Europe", script:"Greek", speakers:"~13M",
    tip:"Greek uses its own alphabet with letters like α, β, γ, θ, λ, φ, ψ, ω. Some look like Latin but Θ, Ξ, Ψ, Ω are uniquely Greek.",
    confusables:["Coptic","Armenian","Georgian","Hebrew","Cyrillic languages"],
    quotes:[{s:"Η αρχή είναι το ήμισυ του παντός.",t:"The beginning is half of everything."},{s:"Γνώθι σαυτόν.",t:"Know thyself."},{s:"Ο χρόνος είναι χρήμα.",t:"Time is money."}]},
  { name:"Albanian", family:"Indo-European (isolate)", region:"Europe", script:"Latin", speakers:"~7.5M",
    tip:"Albanian is a language isolate in Indo-European — related to no other living language. Look for the letters ë (schwa) and the digraphs dh, gj, ll, nj, rr, sh, th, xh, zh.",
    confusables:["Romanian","Serbian","Macedonian","Croatian","Bulgarian"],
    quotes:[{s:"Ku ka dashuri, ka jetë.",t:"Where there is love, there is life."},{s:"Dija është fuqia më e madhe.",t:"Knowledge is the greatest power."},{s:"Kush punon, fitton.",t:"He who works, gains."}]},
  { name:"Basque", family:"Language isolate", region:"Europe", script:"Latin", speakers:"~750K",
    tip:"Basque (Euskara) is completely unrelated to any other language. Look for the letter combination 'tx' (pronounced 'ch'), 'tz', 'ts', and frequent use of 'k' and 'z'. Words ending in -a, -ak, -ean are common.",
    confusables:["Spanish","Catalan","Galician","French","Occitan"],
    quotes:[{s:"Nork bere burua ezagutzen duena, jakintsu da.",t:"He who knows himself is wise."},{s:"Hitza hitz, ardoa ardo.",t:"A word is a word, wine is wine — keep your promises."},{s:"Lan egiten duenak, irabazten du.",t:"He who works, earns."}]},
  { name:"Georgian", family:"Kartvelian", region:"Caucasus", script:"Georgian", speakers:"~4M",
    tip:"Georgian script is one of the world's most distinctive — round asymmetric letters with curving arms. No capitals. Looks almost like decorated spirals.",
    confusables:["Armenian","Amharic","Tigrinya","Greek","Hebrew"],
    quotes:[{s:"ენა კაცს ჰყავს მონად, ჭკუა კი ბატონად.",t:"The tongue is man's servant, but wisdom is his master."},{s:"ვარდი ეკლის გარეშე არ მოდის.",t:"A rose does not come without thorns."}]},
  { name:"Armenian", family:"Indo-European (isolate)", region:"Caucasus", script:"Armenian", speakers:"~8M",
    tip:"Armenian has its own unique alphabet invented in 405 AD. Letters have a medieval angular quality with distinctive shapes like Փ, Ձ, Ղ.",
    confusables:["Georgian","Greek","Amharic","Hebrew","Coptic"],
    quotes:[{s:"Ո՛չ ոք կ'ապրի քո կյանքը, քեզ համար.",t:"No one will live your life for you."},{s:"Ժամանակ ոչ ոք չի կարող գնել:",t:"No one can buy time."}]},

  // ── SEMITIC ──
  { name:"Arabic", family:"Semitic", region:"Middle East / Africa", script:"Arabic", speakers:"~422M",
    tip:"Arabic is right-to-left, letters connect cursively. Dots above/below letters are key. No short vowels are written.",
    confusables:["Persian (Farsi)","Urdu","Pashto","Uyghur","Kurdish"],
    quotes:[{s:"من لم يعرف كيف يقف على المرتفعات لم يعش.",t:"He who has not learned to stand on the heights has not truly lived."},{s:"العلم في الصغر كالنقش على الحجر.",t:"Learning in youth is like engraving on stone."},{s:"اطلبوا العلم من المهد إلى اللحد.",t:"Seek knowledge from the cradle to the grave."}]},
  { name:"Hebrew", family:"Semitic", region:"Middle East", script:"Hebrew", speakers:"~9M",
    tip:"Hebrew is right-to-left with a block-like 22-letter alphabet. Unlike Arabic it's not cursively connected — look for square letterforms.",
    confusables:["Arabic","Yiddish","Aramaic","Amharic","Maltese"],
    quotes:[{s:"אם תרצו, אין זו אגדה.",t:"If you will it, it is no dream."},{s:"כל הדרכים ארוכות לאדם עייף.",t:"All roads are long to a tired person."},{s:"מי שמחפש חבר בלי פגמים נשאר בלי חברים.",t:"He who seeks a friend without faults remains without friends."}]},
  { name:"Amharic", family:"Semitic", region:"Africa", script:"Ethiopic", speakers:"~57M",
    tip:"Amharic uses the Ethiopic (Ge'ez) script — round, circular characters unlike any other writing system. Each symbol is a consonant+vowel syllable.",
    confusables:["Tigrinya","Tigre","Hebrew","Georgian","Sinhala"],
    quotes:[{s:"ብዙ ሲሄዱ ይደርሳሉ፤ ጥቂት ሲሄዱ ይቀራሉ።",t:"Those who keep going will arrive; those who give up will remain behind."},{s:"ዕውቀት ሲጨምር ትዕቢት ይቀንሳል።",t:"As knowledge increases, arrogance decreases."},{s:"ፍቅር ተራራን ያንቀሳቅሳል።",t:"Love moves mountains."}]},
  { name:"Tigrinya", family:"Semitic", region:"Africa", script:"Ethiopic", speakers:"~9M",
    tip:"Tigrinya uses the same Ethiopic (Ge'ez) script as Amharic — circular syllabic characters. Very hard to distinguish from Amharic visually; vocabulary and specific character combinations differ.",
    confusables:["Amharic","Tigre","Hebrew","Georgian","Armenian"],
    quotes:[{s:"ዝሓለፈ ዝሓለፈ፤ ወደፊት ዝጸንሕ ዝጸንሕ።",t:"What has passed has passed; what lies ahead awaits."},{s:"ብትዕግስቲ እቲ ዝኸበደ ሽግር ይሓልፍ።",t:"With patience, even the heaviest hardship passes."}]},

  // ── SINO-TIBETAN ──
  { name:"Mandarin Chinese", family:"Sino-Tibetan", region:"East Asia", script:"Chinese (Simplified)", speakers:"~920M",
    tip:"Simplified Chinese uses streamlined characters with fewer strokes. No spaces between words — characters flow continuously.",
    confusables:["Cantonese","Japanese","Wu Chinese","Classical Chinese","Korean"],
    quotes:[{s:"千里之行，始于足下。",t:"A journey of a thousand miles begins with a single step."},{s:"学而不思则罔，思而不学则殆。",t:"Learning without thought is labor lost; thought without learning is dangerous."},{s:"己所不欲，勿施于人。",t:"Do not do to others what you do not want done to yourself."}]},
  { name:"Cantonese", family:"Sino-Tibetan", region:"East Asia", script:"Chinese (Traditional)", speakers:"~85M",
    tip:"Cantonese uses Traditional Chinese — more strokes than Simplified. Look for 為, 來, 國 instead of 为, 来, 国.",
    confusables:["Mandarin Chinese","Japanese","Wu Chinese","Korean","Classical Chinese"],
    quotes:[{s:"路遙知馬力，日久見人心。",t:"Distance tests a horse's strength; time reveals a person's heart."},{s:"一步一腳印。",t:"One step, one footprint — take things one step at a time."},{s:"天下無難事，只怕有心人。",t:"Nothing is difficult to a determined person."}]},
  { name:"Tibetan", family:"Tibeto-Burman", region:"Central Asia", script:"Tibetan", speakers:"~6M",
    tip:"Tibetan script has stacked letter clusters (consonants piled vertically) and many silent prefix consonants. The stacking pattern makes it unlike any other script.",
    confusables:["Dzongkha","Myanmar (Burmese)","Mongolian","Georgian","Amharic"],
    quotes:[{s:"རང་གི་སེམས་ལ་རང་གིས་དབང་བྱེད་མི་ཤེས་ན་སྐྱིད་པ་ཡོང་གི་མེད།",t:"If you cannot master your own mind, happiness will not come."},{s:"ཤེས་རབ་ནི་གཏེར་མཆོག་ཡིན།",t:"Wisdom is the supreme treasure."}]},
  { name:"Dzongkha", family:"Tibeto-Burman", region:"South Asia", script:"Tibetan", speakers:"~640K",
    tip:"Dzongkha (Bhutan's national language) uses the same Tibetan script as Tibetan. The stacked letter clusters and horizontal strokes are identical — virtually indistinguishable visually.",
    confusables:["Tibetan","Myanmar (Burmese)","Mongolian","Khmer","Lao"],
    quotes:[{s:"གེས་བཟང་གིས་རང་ཉིད་ལ་ཕན་ཐོགས་ཡོད།",t:"Good deeds benefit oneself."},{s:"ཤེས་ཡོན་ནི་ནོར་བུ་ལས་ཀྱང་རིན་ཐང་ཆེ།",t:"Knowledge is more precious than jewels."}]},

  // ── EAST ASIA ──
  { name:"Japanese", family:"Japonic", region:"East Asia", script:"Japanese", speakers:"~125M",
    tip:"Japanese mixes three scripts: Hiragana (curved: あいう), Katakana (angular: アイウ), and Kanji. The simultaneous mix is uniquely Japanese.",
    confusables:["Mandarin Chinese","Cantonese","Korean","Classical Chinese","Wu Chinese"],
    quotes:[{s:"七転び八起き。",t:"Fall seven times, stand up eight."},{s:"継続は力なり。",t:"Continuity is power."},{s:"急がば回れ。",t:"More haste, less speed."}]},
  { name:"Korean", family:"Koreanic", region:"East Asia", script:"Korean", speakers:"~82M",
    tip:"Korean (Hangul) uses geometric blocks of circles and lines. Each block is a syllable. The round ㅇ and ㅎ are very distinctive.",
    confusables:["Japanese","Mandarin Chinese","Cantonese","Mongolian","Tibetan"],
    quotes:[{s:"시작이 반이다.",t:"Starting is half the battle."},{s:"세 살 버릇 여든까지 간다.",t:"Habits formed at three last until eighty."},{s:"티끌 모아 태산.",t:"Many a little makes a mickle."}]},
  { name:"Mongolian", family:"Mongolic", region:"East Asia", script:"Cyrillic", speakers:"~6M",
    tip:"Mongolian Cyrillic looks like Russian but uses Ү, Ө not in standard Russian. Words are longer and vocabulary is unlike Slavic.",
    confusables:["Russian","Bulgarian","Ukrainian","Kazakh","Serbian"],
    quotes:[{s:"Эрдэм мэдлэг — далай, тэвчээр — онгоц.",t:"Knowledge is the ocean, patience is the boat."},{s:"Номын хүч — зэвсгийн хүчнээс хүчтэй.",t:"The power of books is stronger than the power of weapons."}]},

  // ── SOUTHEAST ASIA ──
  { name:"Vietnamese", family:"Austroasiatic", region:"Southeast Asia", script:"Latin (tonal)", speakers:"~96M",
    tip:"Vietnamese uses Latin with an extraordinary number of stacked diacritical marks like ộ, ẫ, ướ. No other Latin-script language looks like this.",
    confusables:["Hmong","Thai","Tagalog","Malay","Indonesian"],
    quotes:[{s:"Có công mài sắt, có ngày nên kim.",t:"With enough perseverance, iron can be ground into a needle."},{s:"Học thầy không tày học bạn.",t:"Learning from a teacher is not as good as learning from friends."},{s:"Lời nói không mất tiền mua.",t:"Words cost nothing."}]},
  { name:"Thai", family:"Kra-Dai", region:"Southeast Asia", script:"Thai", speakers:"~61M",
    tip:"Thai has rounded characters with small circles and loops, no spaces between words, and vowels that appear above, below, or around consonants.",
    confusables:["Khmer","Lao","Myanmar (Burmese)","Kannada","Sinhala"],
    quotes:[{s:"ทางไกลเริ่มต้นด้วยก้าวแรก",t:"A long road begins with the first step."},{s:"น้ำขึ้นให้รีบตัก",t:"When the water rises, hurry to fetch it — seize the moment."},{s:"ความพยายามอยู่ที่ไหน ความสำเร็จอยู่ที่นั่น",t:"Where there is perseverance, there is success."}]},
  { name:"Lao", family:"Kra-Dai", region:"Southeast Asia", script:"Lao", speakers:"~7M",
    tip:"Lao script is very similar to Thai — both have circular characters, no spaces between words, and stacked vowels. Lao letters are rounder and simpler than Thai with fewer characters.",
    confusables:["Thai","Khmer","Myanmar (Burmese)","Sinhala","Tamil"],
    quotes:[{s:"ຄວາມອົດທົນ ຄືກຸນແຈສູ່ຄວາມສໍາເລັດ.",t:"Patience is the key to success."},{s:"ຮູ້ຈັກໂຕເອງ ຄືຮູ້ຈັກໂລກ.",t:"To know yourself is to know the world."}]},
  { name:"Khmer", family:"Austroasiatic", region:"Southeast Asia", script:"Khmer", speakers:"~18M",
    tip:"Khmer has many circular/looping shapes like Thai but more angular and elaborate. Distinctive 'subscript' consonant forms appear below the main line.",
    confusables:["Thai","Myanmar (Burmese)","Kannada","Telugu","Sinhala"],
    quotes:[{s:"បើចង់ឆ្ងាញ់ ត្រូវអត់ធ្មត់រង់ចាំ។",t:"If you want something good, you must be patient and wait."},{s:"ដើរម្តងមួយជំហាន ក៏ដល់ផង។",t:"Walk one step at a time, and you will still arrive."}]},
  { name:"Myanmar (Burmese)", family:"Tibeto-Burman", region:"Southeast Asia", script:"Myanmar", speakers:"~43M",
    tip:"Myanmar script is made of circles and rounded strokes — similar to Khmer but rounder. Perfectly circular letters ၀, ဝ are a giveaway.",
    confusables:["Khmer","Thai","Sinhala","Kannada","Telugu"],
    quotes:[{s:"ကြိုးစားသမျှ အောင်မြင်မည်။",t:"Whatever you strive for, you will achieve."},{s:"ပညာသည် ချမ်းသာကြွယ်ဝမှုထက် တန်ဖိုးကြီးသည်။",t:"Knowledge is more valuable than wealth."}]},
  { name:"Tagalog", family:"Austronesian", region:"Southeast Asia", script:"Latin", speakers:"~82M",
    tip:"Tagalog uses Latin without special characters. Look for the very frequent word 'ng' (a marker), 'mga' (plural marker), and the affixes -um-, mag-, -an, -in attached to roots.",
    confusables:["Indonesian","Malay","Hawaiian","Māori","Cebuano"],
    quotes:[{s:"Ang hindi marunong lumingon sa pinanggalingan ay hindi makakarating sa paroroonan.",t:"One who does not look back at where they came from will not reach their destination."}]},
  { name:"Malay", family:"Austronesian", region:"Southeast Asia", script:"Latin", speakers:"~290M",
    tip:"Malay uses clean Latin script without special characters. Look for prefixes me-, pe-, ber-, ter- and suffixes -kan, -an, -i. The words 'dan' (and), 'yang' (which), 'di' (at) appear very frequently.",
    confusables:["Indonesian","Tagalog","Hawaiian","Māori","Iban"],
    quotes:[{s:"Biar lambat asal selamat.",t:"Better slow than sorry."},{s:"Bahasa jiwa bangsa.",t:"Language is the soul of the nation."},{s:"Ikut hati mati, ikut rasa binasa.",t:"Follow the heart and die — use wisdom instead."}]},
  { name:"Indonesian", family:"Austronesian", region:"Southeast Asia", script:"Latin", speakers:"~270M",
    tip:"Indonesian uses clean Latin without special characters, very similar to Malay. Look for prefixes me-, di-, ke-, ber- and suffixes -kan, -an. Words like 'dan', 'yang', 'tidak' appear constantly.",
    confusables:["Malay","Tagalog","Javanese","Hawaiian","Māori"],
    quotes:[{s:"Bersatu kita teguh, bercerai kita runtuh.",t:"United we stand, divided we fall."},{s:"Air beriak tanda tak dalam.",t:"Rippling water is a sign of shallowness — empty vessels make the most noise."}]},
  { name:"Javanese", family:"Austronesian", region:"Southeast Asia", script:"Latin", speakers:"~98M",
    tip:"Javanese uses Latin in modern contexts. Look for the letters dh and th (retroflex sounds), the word 'iku' (that), and frequent vowel 'e' (schwa). Has its own traditional script but Latin is common.",
    confusables:["Indonesian","Malay","Sundanese","Tagalog","Balinese"],
    quotes:[{s:"Alon-alon waton kelakon.",t:"Slowly but surely."},{s:"Urip iku urup.",t:"Life is a flame — live to give light to others."},{s:"Sapa nandur bakal ngundhuh.",t:"He who plants will harvest."}]},
  { name:"Tetum", family:"Austronesian", region:"Southeast Asia (Timor-Leste)", script:"Latin", speakers:"~1.5M",
    tip:"Tetum uses clean Latin script with no special characters. Look for the very frequent word 'iha' (in/at/there is), 'mak' (which/that), and '-na' suffixes. Portuguese loanwords mixed with Austronesian roots give it a unique feel.",
    confusables:["Indonesian","Malay","Tagalog","Māori","Hawaiian"],
    quotes:[{s:"Hafoin udan mak loron sai.",t:"After rain, the sun comes out."},{s:"Ema ne'ebé keta lakon nia kultura, keta lakon nia an.",t:"A person who loses their culture loses themselves."},{s:"Hamutuk ita forte liu.",t:"Together we are stronger."}]},

  // ── SOUTH ASIA ──
  { name:"Hindi", family:"Indo-Iranian", region:"South Asia", script:"Devanagari", speakers:"~600M",
    tip:"Hindi uses Devanagari — characters hang from a horizontal line at the top. The continuous top bar connecting letters is the key visua
